export const stocks = [
  {
    ticker: "NVDA",
    name: "NVIDIA",
    price: "$891.20",
    change: "+4.2%",
    up: true,
    tag: "🔥 AI powerhouse",
    news: "NVIDIA chips power 80% of global AI infrastructure. Blackwell is sold out through 2026.",
    risk: "Medium",
    recommended: 150,
  },
  {
    ticker: "AAPL",
    name: "Apple",
    price: "$228.00",
    change: "+0.8%",
    up: true,
    tag: "🍎 Steady giant",
    news: "Apple Intelligence rollout picking up steam. Services revenue hit a new all-time high.",
    risk: "Low",
    recommended: 100,
  },
  {
    ticker: "GOLD",
    name: "Gold",
    price: "$2,340/oz",
    change: "+0.6%",
    up: true,
    tag: "🥇 Safe haven",
    news: "Geopolitical tensions pushing gold to record highs. Central banks keep accumulating.",
    risk: "Low",
    recommended: 200,
  },
  {
    ticker: "MSCI",
    name: "MSCI World ETF",
    price: "$45.80",
    change: "+0.3%",
    up: true,
    tag: "🌍 The classic",
    news: "The most diversified global index. Perfect starting point. Low stress, solid returns.",
    risk: "Low",
    recommended: 300,
  },
  {
    ticker: "BTC",
    name: "Bitcoin ETF",
    price: "$61,200",
    change: "-2.1%",
    up: false,
    tag: "⚡ High volatility",
    news: "Pullback after recent highs. BTC ETFs have pulled in $12B in positive flows this month.",
    risk: "High",
    recommended: 50,
  },
];
