export const stocks = [
  {
    ticker: "NVDA",
    name: "NVIDIA",
    price: "€891.20",
    change: "+4.2%",
    up: true,
    tag: "🔥 IA imparable",
    news: "Los chips de NVIDIA alimentan el 80% de la IA mundial. Blackwell agota stock hasta 2026.",
    risk: "Medio",
    recommended: 150,
  },
  {
    ticker: "IAG",
    name: "Iberia (IAG)",
    price: "€2.41",
    change: "+1.8%",
    up: true,
    tag: "✈️ España vuela",
    news: "Récord de turistas en España. IAG sube beneficios un 34% este trimestre.",
    risk: "Bajo",
    recommended: 80,
  },
  {
    ticker: "GOLD",
    name: "Oro",
    price: "€2,340/oz",
    change: "+0.6%",
    up: true,
    tag: "🥇 Refugio seguro",
    news: "Tensiones geopolíticas disparan el oro a máximos históricos. Los bancos centrales acumulan.",
    risk: "Bajo",
    recommended: 200,
  },
  {
    ticker: "MSCI",
    name: "MSCI World ETF",
    price: "€45.80",
    change: "+0.3%",
    up: true,
    tag: "🌍 El clásico",
    news: "El índice global más diversificado. Perfecto para empezar. Sin estrés.",
    risk: "Bajo",
    recommended: 300,
  },
  {
    ticker: "BTC",
    name: "Bitcoin ETF",
    price: "€61,200",
    change: "-2.1%",
    up: false,
    tag: "⚡ Alta volatilidad",
    news: "Corrección tras máximos. Los ETFs de BTC acumulan 12B$ en flujos positivos este mes.",
    risk: "Alto",
    recommended: 50,
  },
];
